# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-09 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 9, 14, 18, 20, 973523, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
