# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-09 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_time_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Time'),
        ),
    ]
