# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20161009_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='time',
        ),
        migrations.AddField(
            model_name='time',
            name='Rooms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Rooms'),
        ),
    ]
