# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20161010_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='Rooms',
        ),
        migrations.AddField(
            model_name='time',
            name='Rooms',
            field=models.ManyToManyField(null=True, to='tracker.Rooms'),
        ),
    ]
