# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20161010_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='Rooms',
            field=models.ManyToManyField(to='tracker.Rooms'),
        ),
    ]
