# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20161010_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='rooms',
            new_name='Rooms',
        ),
    ]
