# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20161010_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='time1',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time10',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time11',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time12',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time2',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time3',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time4',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time5',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time6',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time7',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time8',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time9',
        ),
        migrations.AddField(
            model_name='time',
            name='time',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
